apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/danmcfan/planet-emu-fast-api:latest
          command:
            - "/bin/sh"
            - "-c"
            - "celery -A planet_emu.celery worker --loglevel=info"
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis-svc:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis-svc:6379/0
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
      imagePullSecrets:
        - name: ghcr
